#!/usr/bin/env bash
set -euo pipefail

if [ ${1:-''} == 'WRITE' ]; then
  sudo apt update
  sudo apt upgrade -y

  sudo apt install -y openssh-server
  sudo systemctl enable --now ssh

  sudo apt install -y ruby

  sudo mkdir -p $(bin/fstab-mnt-path)

  sudo cp /etc/fstab /etc/fstab.bak-$(date +%s)
  sudo sh -c 'bin/fstab > fstab.tmp'
  sudo mv fstab.tmp /etc/fstab
  sudo mount -a

  sudo crontab -l || true | bin/crontab | sudo crontab -

  touch ~/frame-slideshow
  chmod 0700 ~/frame-slideshow
  bin/slideshow > ~/frame-slideshow

  bin/autostart > ~/.config/autostart/frame-slideshow.desktop
else
  echo 'sudo mkdir -p $(bin/fstab-mnt-path)'
  bin/fstab-mnt-path
  echo

  echo '/etc/fstab'
  bin/fstab
  echo

  echo 'sudo crontab -l | bin/crontab | sudo crontab -'
  sudo crontab -l || true | bin/crontab
  echo

  echo '~/frame-slideshow'
  bin/slideshow
  echo

  echo '~/.config/autostart/frame-slideshow.desktop'
  bin/autostart
fi

# TODO
# auto login (/etc/gdm3/custom.conf)
