#!/usr/bin/env bash
set -euo pipefail

if [ ${1:-''} == 'WRITE' ]; then
  gsettings set org.gnome.desktop.notifications show-banners false
  sudo apt install -y openssh-server cifs-utils
  sudo systemctl enable --now ssh

  sudo apt install -y ruby

  sudo mkdir -p $(bin/fstab-mnt-path)

  sudo cp /etc/fstab ~/fstab.bak-$(date +%s)
  sudo sh -c 'bin/fstab > fstab.tmp'
  sudo mv fstab.tmp /etc/fstab
  sudo mount -a

  sudo crontab -l > ~/crontab.bak-$(date +%s)
  sudo crontab -l | bin/crontab | sudo crontab -

  touch ~/frame-slideshow
  chmod 0700 ~/frame-slideshow
  bin/slideshow > ~/frame-slideshow

  sudo sh -c 'bin/systemd > systemd.tmp'
  sudo mv systemd.tmp /etc/systemd/system/frame-slideshow.service
  sudo systemctl daemon-reload
  sudo systemctl enable --now frame-slideshow.service
else
  echo 'sudo mkdir -p $(bin/fstab-mnt-path)'
  bin/fstab-mnt-path
  echo

  echo '/etc/fstab'
  bin/fstab
  echo

  echo 'sudo crontab -l | bin/crontab | sudo crontab -'
  sudo crontab -l | bin/crontab
  echo

  echo '~/frame-slideshow'
  bin/slideshow
  echo

  echo '/etc/systemd/system/frame-slideshow.service'
  bin/systemd
  echo
fi

# TODO
# auto login (/etc/gdm3/custom.conf)
