#!/usr/bin/env bash
set -euo pipefail

if [ ${1:-''} == 'WRITE' ]; then
  sudo apt update
  sudo apt upgrade -y

  sudo apt install -y openssh-server
  sudo systemctl enable --now ssh

  sudo apt install -y ruby

  sudo sh -c 'bin/fstab > /etc/fstab'
  sudo mount -a

  sudo crontab -l | bin/crontab | sudo crontab -

  touch ~/frame-slideshow
  chmod 0700 ~/frame-slideshow
  bin/slideshow > ~/frame-slideshow

  bin/autostart > ~/.config/autostart/frame-slideshow.desktop
else
  echo '/etc/fstab'
  bin/fstab
  echo

  echo 'sudo crontab -l | bin/crontab | sudo crontab -'
  sudo crontab -l | bin/crontab
  echo

  echo '~/frame-slideshow'
  bin/slideshow
  echo

  echo '~/.config/autostart/frame-slideshow.desktop'
  bin/autostart
fi

# TODO
# auto login (/etc/gdm3/custom.conf)
